### ISSUE TITLE
NPM Install Still Not working

### ISSUE THREAD

**Issue by Makosak** [cutting-room-floor/tilestream#149]
I've spent a while troubleshooting my tilestream install, and have still been getting a suite of errors. 

First, specs: npm version 2.10.1, node version 0.12.4. Mac 10.8.5. Node installed with Homebrew.
Troubleshooting already done with below:
$ npm install sqlite3
$ npm install mbtiles
$ npm install jsdom
$ npm install uglify-js
$ npm install connect
$ npm install qs
$ npm install mime
$ install cmake  [another thread suggested brew wasn't bringing in this dependency for gyp]
also deleted node-module folder and reinstalled, multiple times. 

There is usually some form of below. (also if I try npm install -g tilestream)
$ npm install  tilestream

npm WARN engine tilestream@1.1.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine tilelive@4.3.3: wanted: {"node":">= 0.6.0 && < 0.9.0"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine bones@1.3.29: wanted: {"node":"0.4 || 0.6 || 0.8 || 0.10"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/Cellar/node/0.12.4/bin/node --eval require('/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node')
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
child_process: customFds option is deprecated, use stdio instead.
Error: No developer directory found at /Developer. Run /usr/bin/xcode-select to update the developer directory path.

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

Error: No developer directory found at /Developer. Run /usr/bin/xcode-select to update the developer directory path.

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c:8542:26: warning: unused
      variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Makosak/.node-gyp/0.12.4/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Makosak/.node-gyp/0.12.4/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Makosak/.node-gyp/0.12.4/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Makosak/.node-gyp/0.12.4/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
2 errors generated.
make: **\* [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "/usr/local/Cellar/node/0.12.4/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/0.12.4/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 12.5.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/0.12.4/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/lib/node_modules/tilestream/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "tilestream"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@2.2.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@2.2.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    ~/code/MapBox/npm-debug.log

**Comment by Makosak** [comment]
A friend with a different config was able to replicate the error above, with the same troubleshooting attempts. I thought it was my outdated XCode but that wasn't the case.

**Comment by kyroskoh** [comment]
I have encountered this problem before especially when installing sqlite3 via npm. I recommend to use NodeJS 0.10.x, it solved my problem. I also managed to compile sqlite3 separately and manage to copy sqlite3 in node_modules over to avoid this problem.

If you wish to have a copy of my current build for tilestream, let me know so I can upload it.

**Comment by devonjs** [comment]
ran into the same problems, had to use Node 0.10.x, check this repo to easily switch between your version of node and another one: https://github.com/creationix/nvm

got this to work switching over 0.10.x
