### ISSUE TITLE
Node not starting on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by SirePi** [cutting-room-floor/tilestream#153]
On a new Ubuntu server I get the following error when trying to start Tilestream

/tilestream/node_modules/connect/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/tilestream/node_modules/connect/lib/middleware/bodyParser.js:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

using Node 0.10.28;
on another machine with the same Node version, it works without issues.

What might be wrong?

Thanks

**Comment by SirePi** [comment]
Starting node with option --harmony solves the issue, but is it normal?
