### ISSUE TITLE
install without error, but run failed. const Stringify = require('./stringify'); SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by hoogw** [cutting-room-floor/tilestream#154]
window 7 and windows server 2012,
install tilestream without any error message. 
But when I run it, it error out. 
To verify this is  bug, I did both windows 7 and server 2012, both give the exact same error. 

c:\tilestream>node index.js

error:

c:\tilestream\node_modules\connect\node_modules\qs\lib\index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\tilestream\node_modules\connect\lib\middleware\bod
yParser.js:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by hoogw** [comment]
I found the problem is in connect folder, C:\tilestream\node_modules\connect, if I replace connect folder with the previously working copy's connect folder, it will works.  If I use "npm install" then node index.js, will always get error message above

**Comment by wrigby** [comment]
I just ran into this as well using node 0.10.36 (CentOS 6 EPEL packages). Using the `--harmony` option fixes it in my case:

```
$ node --harmony index.js
```

**Comment by hoogw** [comment]
wrigby, great !  I test -- harmony option on windows 7 and windows server 2012, both worked 
So the solution is add option -- harmony
